export const Icons = {
	disabled: "hugeicons:unavailable",
	enabled: "hugeicons:checkmark-circle-03",
	file: "hugeicons:file-02",
	email: "hugeicons:at",
	github: "hugeicons:github-01",
	instagram: "hugeicons:instagram",
	key: "hugeicons:key-01",
	left: "hugeicons:arrow-left-02",
	right: "hugeicons:arrow-right-02",
	settings: "hugeicons:settings-01",
	security: "hugeicons:security",
	linkedIn: "hugeicons:linkedin-01",
	location: "hugeicons:location-01",
	lock: "hugeicons:square-lock-01",
	login: "hugeicons:login-02",
	logout: "hugeicons:logout-02",
	mail: "hugeicons:mail-02",
	phone: "hugeicons:smart-phone-01",
	notifications: "hugeicons:notification-01",
	message: "hugeicons:message-02",
	user: "hugeicons:user-03",
	computer: "hugeicons:computer",
	googleLogo: "logos:google-icon",
	githubLogo: "logos:github-icon",
	moreVertical: "hugeicons:more-vertical",
};
